### ISSUE TITLE
ec2_info.py does not return user-data

### ISSUE THREAD

**Issue by freimer** [saltstack/salt-contrib#117]
User data can be of interest and importance, but ec2_info leaves out this portion of the data.

**Comment by scaissie** [comment]
If no user data is defined for that instance, you get a 404, which prevents any grains from being added:

# curl http://169.254.169.254//latest/user-data
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>

**Comment by freimer** [comment]
I believe I already submitted a fix for this.  If not, I have one I can submit.

**Comment by giannello** [comment]
+1

**Comment by freimer** [comment]
Fixed in PR #119 Let me know if you have problems.

**Comment by dwoz** [comment]
Closing this issue because a fix has been merged.
