### ISSUE TITLE
REST example port

### ISSUE THREAD

**Issue by aanriot** [saltstack/salt-contrib#159]
Hello,

The REST service _proxyminion_rest_example/rest.py_ is listening by default on 8080/tcp.

Though, the following documentation is mentionning 8000/tcp:
https://docs.saltstack.com/en/develop/topics/proxyminion/demo.html

I believe that the documentation (or the code) should be modified accordingly.

Thanks.

**Comment by cro** [comment]
Thank you @aanriot , I fixed the code.
