### ISSUE TITLE
Does ec2_tags.py support EC2 role?

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt-contrib#166]
Does ec2_tags.py support EC2 role? Would be nice to avoid having to manually specify secret and access key.

**Comment by benhosmer** [comment]
Are you referring to IAM roles? From the [doc strings](https://github.com/saltstack/salt-contrib/blob/master/grains/ec2_tags.py#L20-L35) it appears that it does.

**Comment by JensRantil** [comment]
Yepp! Missed that! Thanks!
